### PR TITLE
Add args to be_clean_nav_menu_classes

### PR DESCRIPTION
**Pull request by szepeviktor**
https://developer.wordpress.org/reference/hooks/nav_menu_css_class/

@billerickson Please consider using static analysis.
There are 16 more problems.

### CODE REVIEW

**Comment by billerickson** [comment]
I'm sorry, I'm not familiar with this one. Why do we need to include the additional parameters when they aren't used by our function?

**Comment by szepeviktor** [comment]
I saw `args` at the bottom
https://github.com/billerickson/BE-Starter/blob/4ded53eb84535f3893de6f040af20a71cf3a6ee6/inc/wordpress-cleanup.php#L98-L99

**Comment by billerickson** [comment]
Ah you're right, thank you!

**Comment by szepeviktor** [comment]
Three of the PR-s contain mentions of further problems. Are you interested?

**Comment by billerickson** [comment]
Definitely, any improvements to this theme are appreciated.

**Pull request merged**
